# 服务器配置
server:
  port: 8581
# spring总配置
spring:
  # 数据源配置
  datasource:
    # druid连接池最简单的配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.128:33801/tlmallswarmmymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: tlmalladmin
    password: Tlmall_123456
  # swagger路径匹配策略
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  # redis配置
  redis:
    host: 192.168.3.128 # 服务器地址
    database: 0     # 数据库索引（默认0）
    port: 63791     # 服务器连接端口
    password:       # 连接密码（默认空）
    jedis:          # java-redis驱动
      pool:           # 连接池
        max-active: 8   # 最大连接数（负值表示没有限制）
        max-wait: -1ms  # 最大阻塞等待时间（负值表示没有限制）
        max-idle: 8     # 最大空虚连接数
        min-idle: 0     # 最小空闲连接数
    timeout: 3000ms # 连接超时时间（毫秒）
  # spring-data配置
  data:
    # Elasticsearch配置 ES8以后主要支持代码中配置
    # MongoDB配置
    mongodb:
      host: 192.168.3.128     # mongodb的连接地址
      port: 27011             # mongodb的连接端口号
      username: "usermymall"
      password: 'mymall123'   # 密码必须单引号括起来，否则报错
      database: mymallportal  # mongodb的连接的数据库,别带 “-” 短横线了吧！因为去mongo里面测试中间有符号会指令错误！
  # spring-amqp和spring-data同级，而amqp等同于rabbitMQ
  rabbitmq:
    host: 192.168.3.128
    port: 5671
    virtual-host: mymall      # rabbitmq的虚拟host，【注意】名称一定要和管理页面user可访问的vhost名称保持一致！！！
    username: usermymall
    password: mymall123
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 600MB
# minio配置 (仅供配置类映射属性值使用)
minio:
  endpoint: http://192.168.3.128:9010                 #MinIO服务所在地址
  bucket: mymall                                      #默认存储桶的名称，程序中可根据业务自行创建桶
  accessKey: 0AIK8LX7MOB5DH1RLEWQ                     #访问的key（账号）
  secretKey: w7X2+hpA+Xi5ZNxEK+6zCTQ3SJIFblkBSoaJCj6Y #访问的秘钥（密码）
# Redis自定义key
redis:
  key:
    prefix:
      authCode: "my-mall-portal:authCode:"
    expire:
      authCode: 120                                   # 验证码超期时间
# MyBatis配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
# JWT配置
jwt:
  tokenHeader: Authorization  # JWT存储的请求头
  secret: jwt_123             # JWT加密密钥
  expiration: 86400           # JWT过期时间（60*60*24）
  tokenHead: Bearer           # JWT负载的开头