server:
  port: 8581

spring:
  datasource:
    url: jdbc:mysql://192.168.3.128:33801/tlmallswarmmymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: tlmalladmin
    password: Tlmall_123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
